"""
MT5 tester .set файл үүсгэгч.

.set файл нь UTF-16-LE BOM-той, NEL (0x0a) эсвэл CRLF мөртэй.
Format: InpName=value||default||min||max||F_or_N
  F = optimization enabled
  N = no optimization (only `value` used)

Ашиглалт:
    from make_setfile import write_set
    write_set(path, {"InpTBMEnable": "false", "InpVixEnable": "false"})
"""
from __future__ import annotations

from pathlib import Path


def _value_line(name: str, value) -> str:
    # MT5 bool инпутыг "false"/"true" гэж хүлээн авдаг
    v = str(value)
    if isinstance(value, bool):
        v = "false" if not value else "true"
    return f"{name}={v}||{v}||0||0||N"


def write_set(path: Path, inputs: dict) -> Path:
    lines = [
        "; generated by make_setfile.py",
        *[_value_line(k, v) for k, v in inputs.items()],
    ]
    content = "\r\n".join(lines) + "\r\n"
    data = b"\xff\xfe" + content.encode("utf-16-le")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return path


if __name__ == "__main__":
    import sys, json
    out = Path(sys.argv[1])
    inputs = json.loads(sys.argv[2]) if len(sys.argv) > 2 else {}
    write_set(out, inputs)
    print(f"wrote {out}")
